// Base de receitas inicial — é só um ponto de partida, edite/apague/adicione livremente pela aba "Receitas".
// Cada receita tem uma porção-base (baseServings) e ingredientes proporcionais a ela.
// O app escala tudo automaticamente conforme o número de pessoas informado no planejamento.

const SEED_RECIPES = [
  {
    id: "arroz-branco",
    name: "Arroz branco",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Arroz", qty: 2, unit: "xícara" },
      { name: "Óleo", qty: 1, unit: "colher de sopa" },
      { name: "Alho", qty: 1, unit: "dente" },
    ],
    instructions: [
      "Lave o arroz em água corrente até a água sair mais clara.",
      "Aqueça o óleo numa panela e refogue o alho picado até dourar levemente.",
      "Junte o arroz e refogue por 1-2 minutos, mexendo sempre.",
      "Adicione água quente (o dobro do volume de arroz) e sal a gosto.",
      "Deixe ferver, abaixe o fogo, tampe e cozinhe por 15-18 minutos até secar.",
    ],
  },
  {
    id: "feijao-carioca",
    name: "Feijão carioca",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Feijão carioca", qty: 300, unit: "g" },
      { name: "Alho", qty: 2, unit: "dente" },
      { name: "Cebola", qty: 0.5, unit: "unidade" },
    ],
    instructions: [
      "Deixe o feijão de molho por pelo menos 4 horas (ou de um dia pro outro).",
      "Escorra e cozinhe na panela de pressão com água cobrindo por 2 dedos, por cerca de 20-25 minutos após pegar pressão.",
      "Numa frigideira, refogue o alho e a cebola picados no óleo até dourar.",
      "Misture o refogado no feijão já cozido, tempere com sal e deixe ferver por mais 5-10 minutos.",
    ],
  },
  {
    id: "frango-grelhado",
    name: "Frango grelhado",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Peito de frango", qty: 600, unit: "g" },
      { name: "Alho", qty: 2, unit: "dente" },
      { name: "Limão", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Corte o peito de frango em filés e tempere com alho amassado, suco de limão, sal e pimenta.",
      "Deixe marinar por pelo menos 15 minutos.",
      "Aqueça uma grelha ou frigideira antiaderente em fogo médio-alto.",
      "Grelhe os filés por 5-6 minutos de cada lado, até dourar e cozinhar por dentro.",
    ],
  },
  {
    id: "frango-parmegiana",
    name: "Frango à parmegiana",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Peito de frango", qty: 600, unit: "g" },
      { name: "Molho de tomate", qty: 400, unit: "g" },
      { name: "Queijo mussarela", qty: 200, unit: "g" },
      { name: "Farinha de rosca", qty: 150, unit: "g" },
      { name: "Ovo", qty: 2, unit: "unidade" },
    ],
    instructions: [
      "Corte o peito de frango em bifes finos e tempere com sal e pimenta.",
      "Passe cada bife no ovo batido e depois na farinha de rosca, cobrindo bem.",
      "Frite em óleo quente até dourar dos dois lados, ou asse a 200°C até dourar.",
      "Numa assadeira, coloque uma camada de molho de tomate, os bifes empanados, mais molho por cima e cubra com a mussarela.",
      "Leve ao forno pré-aquecido a 200°C por 15-20 minutos, até o queijo derreter e gratinar.",
    ],
  },
  {
    id: "strogonoff-frango",
    name: "Strogonoff de frango",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Peito de frango", qty: 600, unit: "g" },
      { name: "Creme de leite", qty: 200, unit: "g" },
      { name: "Molho de tomate", qty: 100, unit: "g" },
      { name: "Champignon", qty: 100, unit: "g" },
      { name: "Cebola", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Corte o frango em cubos e tempere com sal e pimenta.",
      "Refogue a cebola picada no óleo até ficar transparente, junte o frango e doure por todos os lados.",
      "Acrescente o champignon fatiado e o molho de tomate, mexendo bem.",
      "Cozinhe em fogo médio por 8-10 minutos, até o frango cozinhar por completo.",
      "Desligue o fogo, misture o creme de leite e sirva na sequência (sem ferver depois de adicionar o creme).",
    ],
  },
  {
    id: "carne-moida",
    name: "Carne moída com batata",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Carne moída", qty: 500, unit: "g" },
      { name: "Batata", qty: 4, unit: "unidade" },
      { name: "Cebola", qty: 1, unit: "unidade" },
      { name: "Tomate", qty: 2, unit: "unidade" },
    ],
    instructions: [
      "Descasque as batatas e corte em cubos médios.",
      "Refogue a cebola picada no óleo até dourar, junte a carne moída e tempere com sal e pimenta.",
      "Cozinhe mexendo até a carne perder a cor rosada e soltar a gordura.",
      "Adicione o tomate picado e as batatas, misture bem.",
      "Junte um pouco de água, tampe e cozinhe em fogo médio-baixo por 20-25 minutos, até as batatas ficarem macias.",
    ],
  },
  {
    id: "bife-acebolado",
    name: "Bife acebolado",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Bife (patinho ou coxão mole)", qty: 600, unit: "g" },
      { name: "Cebola", qty: 2, unit: "unidade" },
      { name: "Alho", qty: 2, unit: "dente" },
    ],
    instructions: [
      "Tempere os bifes com sal, pimenta e alho amassado.",
      "Aqueça a frigideira bem quente com um fio de óleo e sele os bifes rapidamente dos dois lados.",
      "Retire os bifes e reserve.",
      "Na mesma frigideira, refogue as cebolas fatiadas até ficarem douradas e macias.",
      "Volte os bifes pra frigideira, misture com a cebola e cozinhe por mais 1-2 minutos.",
    ],
  },
  {
    id: "peixe-assado",
    name: "Peixe assado",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Filé de peixe", qty: 600, unit: "g" },
      { name: "Limão", qty: 1, unit: "unidade" },
      { name: "Azeite", qty: 2, unit: "colher de sopa" },
    ],
    instructions: [
      "Tempere os filés com sal, pimenta, suco de limão e azeite. Deixe marinar 10 minutos.",
      "Coloque os filés numa assadeira untada.",
      "Leve ao forno pré-aquecido a 200°C por 15-20 minutos, até o peixe ficar opaco e se soltar facilmente com o garfo.",
    ],
  },
  {
    id: "macarrao-bolonhesa",
    name: "Macarrão à bolonhesa",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Macarrão", qty: 500, unit: "g" },
      { name: "Carne moída", qty: 400, unit: "g" },
      { name: "Molho de tomate", qty: 400, unit: "g" },
      { name: "Cebola", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Cozinhe o macarrão em água fervente com sal, conforme instrução da embalagem, até ficar al dente.",
      "Numa panela, refogue a cebola picada no óleo até dourar.",
      "Junte a carne moída e cozinhe até perder a cor rosada, temperando com sal e pimenta.",
      "Adicione o molho de tomate e deixe cozinhar em fogo médio-baixo por 10-15 minutos.",
      "Escorra o macarrão e sirva com o molho bolonhesa por cima.",
    ],
  },
  {
    id: "lasanha",
    name: "Lasanha",
    category: "prato principal",
    baseServings: 6,
    ingredients: [
      { name: "Massa de lasanha", qty: 250, unit: "g" },
      { name: "Carne moída", qty: 500, unit: "g" },
      { name: "Molho de tomate", qty: 400, unit: "g" },
      { name: "Queijo mussarela", qty: 300, unit: "g" },
      { name: "Presunto", qty: 150, unit: "g" },
    ],
    instructions: [
      "Refogue a carne moída temperada até dourar, junte o molho de tomate e cozinhe por 10 minutos.",
      "Se a massa não for pré-cozida, cozinhe rapidamente conforme a embalagem.",
      "Numa assadeira, monte camadas alternando massa, molho com carne, presunto e mussarela, repetindo até acabar os ingredientes.",
      "Finalize com uma camada generosa de mussarela por cima.",
      "Cubra com papel-alumínio e asse a 200°C por 25 minutos; retire o papel e deixe gratinar por mais 10-15 minutos.",
    ],
  },
  {
    id: "omelete",
    name: "Omelete",
    category: "prato principal",
    baseServings: 2,
    ingredients: [
      { name: "Ovo", qty: 4, unit: "unidade" },
      { name: "Queijo mussarela", qty: 50, unit: "g" },
      { name: "Tomate", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Bata os ovos numa tigela com sal e pimenta.",
      "Pique o tomate e o queijo em cubos pequenos e misture aos ovos batidos.",
      "Aqueça uma frigideira antiaderente com um fio de óleo em fogo médio.",
      "Despeje a mistura e cozinhe sem mexer até a base firmar, depois dobre ao meio e cozinhe mais 1-2 minutos.",
    ],
  },
  {
    id: "macarrao-alho-oleo",
    name: "Macarrão alho e óleo com frango desfiado",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Macarrão", qty: 500, unit: "g" },
      { name: "Peito de frango", qty: 400, unit: "g" },
      { name: "Alho", qty: 4, unit: "dente" },
      { name: "Azeite", qty: 3, unit: "colher de sopa" },
    ],
    instructions: [
      "Cozinhe o peito de frango em água com sal até ficar macio, depois desfie.",
      "Cozinhe o macarrão em água fervente com sal até ficar al dente e escorra, reservando um pouco da água do cozimento.",
      "Numa frigideira grande, aqueça o azeite e doure o alho fatiado sem queimar.",
      "Junte o frango desfiado e refogue por 2 minutos.",
      "Adicione o macarrão escorrido, misture bem e ajuste com um pouco da água reservada se ficar seco.",
    ],
  },
  {
    id: "risoto-simples",
    name: "Risoto simples",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Arroz arbório", qty: 2, unit: "xícara" },
      { name: "Caldo de legumes", qty: 1, unit: "l" },
      { name: "Queijo parmesão", qty: 80, unit: "g" },
      { name: "Cebola", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Aqueça o caldo de legumes numa panela à parte e mantenha em fogo baixo.",
      "Refogue a cebola picada no azeite até ficar transparente.",
      "Junte o arroz arbório e refogue por 1-2 minutos, até ficar translúcido nas bordas.",
      "Adicione o caldo quente aos poucos, uma concha por vez, mexendo sempre e só acrescentando mais quando o líquido anterior secar.",
      "Repita até o arroz ficar cremoso e al dente (cerca de 18-20 minutos). Desligue o fogo e misture o parmesão ralado.",
    ],
  },
  {
    id: "salada-crua",
    name: "Salada crua variada",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Alface", qty: 1, unit: "pé" },
      { name: "Tomate", qty: 2, unit: "unidade" },
      { name: "Pepino", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Lave bem todas as folhas e legumes.",
      "Rasgue ou corte a alface em pedaços, e fatie o tomate e o pepino.",
      "Misture tudo numa saladeira e tempere com sal, azeite e vinagre (ou limão) na hora de servir.",
    ],
  },
  {
    id: "legumes-refogados",
    name: "Legumes refogados",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Cenoura", qty: 2, unit: "unidade" },
      { name: "Abobrinha", qty: 2, unit: "unidade" },
      { name: "Alho", qty: 1, unit: "dente" },
    ],
    instructions: [
      "Corte a cenoura e a abobrinha em rodelas ou cubos pequenos.",
      "Aqueça um fio de óleo numa frigideira e refogue o alho picado até perfumar.",
      "Junte a cenoura primeiro e refogue por 3-4 minutos.",
      "Adicione a abobrinha, tempere com sal e cozinhe por mais 5-6 minutos, até os legumes ficarem macios mas com textura.",
    ],
  },

  // ---- Proteínas extras (frango, boi, peixe, porco) ----
  {
    id: "frango-milanesa",
    name: "Frango à milanesa",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Peito de frango", qty: 600, unit: "g" },
      { name: "Farinha de trigo", qty: 100, unit: "g" },
      { name: "Ovo", qty: 2, unit: "unidade" },
      { name: "Farinha de rosca", qty: 150, unit: "g" },
    ],
    instructions: [
      "Corte o peito de frango em bifes finos e tempere com sal, pimenta e alho em pó.",
      "Passe cada bife na farinha de trigo, depois no ovo batido e por fim na farinha de rosca, pressionando bem.",
      "Frite em óleo quente até dourar dos dois lados, uns 3-4 minutos cada lado.",
      "Escorra em papel-toalha antes de servir.",
    ],
  },
  {
    id: "frango-assado-ervas",
    name: "Frango assado com ervas e limão",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Sobrecoxa de frango", qty: 800, unit: "g" },
      { name: "Limão", qty: 1, unit: "unidade" },
      { name: "Alho", qty: 3, unit: "dente" },
      { name: "Azeite", qty: 2, unit: "colher de sopa" },
    ],
    instructions: [
      "Tempere as sobrecoxas com sal, pimenta, alho amassado, suco de limão e azeite. Deixe marinar por pelo menos 20 minutos.",
      "Arrume numa assadeira untada, com a pele voltada para cima.",
      "Leve ao forno pré-aquecido a 200°C por 35-40 minutos, até dourar e a carne soltar do osso facilmente.",
      "Regue com o próprio molho da assadeira antes de servir.",
    ],
  },
  {
    id: "carne-panela-desfiada",
    name: "Carne de panela desfiada",
    category: "prato principal",
    baseServings: 5,
    ingredients: [
      { name: "Acém", qty: 800, unit: "g" },
      { name: "Cebola", qty: 1, unit: "unidade" },
      { name: "Alho", qty: 3, unit: "dente" },
      { name: "Tomate", qty: 2, unit: "unidade" },
    ],
    instructions: [
      "Tempere a carne com sal, pimenta e alho amassado.",
      "Doure a carne por igual numa panela de pressão com um fio de óleo.",
      "Junte a cebola e o tomate picados, refogue por 2 minutos.",
      "Cubra com água, tampe a panela e cozinhe por 40-45 minutos após pegar pressão, até a carne ficar bem macia.",
      "Retire a carne, desfie com dois garfos e volte pra panela, misturando com o molho até apurar.",
    ],
  },
  {
    id: "iscas-carne-pimentao",
    name: "Iscas de carne com pimentão",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Bife (patinho ou coxão mole)", qty: 600, unit: "g" },
      { name: "Pimentão", qty: 2, unit: "unidade" },
      { name: "Cebola", qty: 1, unit: "unidade" },
      { name: "Alho", qty: 2, unit: "dente" },
    ],
    instructions: [
      "Corte a carne em tiras finas (iscas) e tempere com sal, pimenta e alho amassado.",
      "Aqueça a frigideira bem quente com um fio de óleo e sele as iscas rapidamente, em porções, sem lotar a frigideira.",
      "Retire a carne e reserve. Na mesma frigideira, refogue a cebola e o pimentão fatiados até murcharem.",
      "Volte a carne pra frigideira, misture e cozinhe por mais 1-2 minutos antes de servir.",
    ],
  },
  {
    id: "file-peixe-grelhado",
    name: "Filé de peixe grelhado com limão e alho",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Filé de peixe", qty: 600, unit: "g" },
      { name: "Limão", qty: 1, unit: "unidade" },
      { name: "Alho", qty: 2, unit: "dente" },
    ],
    instructions: [
      "Tempere os filés com sal, pimenta, suco de limão e alho amassado. Deixe descansar 10 minutos.",
      "Aqueça uma frigideira antiaderente com um fio de azeite em fogo médio-alto.",
      "Grelhe os filés por 3-4 minutos de cada lado, até dourar e soltar facilmente com o garfo.",
      "Sirva com um fio de azeite e mais um toque de limão por cima.",
    ],
  },
  {
    id: "peixe-a-dore",
    name: "Peixe à dorê (empanado)",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Filé de peixe", qty: 600, unit: "g" },
      { name: "Ovo", qty: 2, unit: "unidade" },
      { name: "Farinha de trigo", qty: 100, unit: "g" },
    ],
    instructions: [
      "Tempere os filés de peixe com sal, pimenta e limão.",
      "Passe cada filé na farinha de trigo e depois no ovo batido, cobrindo bem.",
      "Frite em óleo quente até dourar dos dois lados, cerca de 3 minutos cada lado.",
      "Escorra em papel-toalha antes de servir.",
    ],
  },
  {
    id: "lombo-porco-assado",
    name: "Lombo de porco assado",
    category: "prato principal",
    baseServings: 5,
    ingredients: [
      { name: "Lombo de porco", qty: 800, unit: "g" },
      { name: "Alho", qty: 3, unit: "dente" },
      { name: "Limão", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Tempere o lombo com sal, pimenta, alho amassado e suco de limão. Deixe marinar por pelo menos 30 minutos (ou de um dia pro outro, se der).",
      "Coloque numa assadeira com um fio de óleo, cobrindo com papel-alumínio.",
      "Asse a 200°C por 40 minutos, retire o papel e deixe dourar por mais 15-20 minutos.",
      "Deixe descansar 5 minutos antes de fatiar.",
    ],
  },
  {
    id: "bisteca-porco-grelhada",
    name: "Bisteca de porco grelhada",
    category: "prato principal",
    baseServings: 4,
    ingredients: [
      { name: "Bisteca de porco", qty: 700, unit: "g" },
      { name: "Alho", qty: 2, unit: "dente" },
      { name: "Limão", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Tempere as bistecas com sal, pimenta, alho amassado e suco de limão. Deixe marinar por 15-20 minutos.",
      "Aqueça bem a grelha ou frigideira com um fio de óleo.",
      "Grelhe as bistecas por 5-6 minutos de cada lado, até dourar e cozinhar por dentro.",
      "Deixe descansar 2-3 minutos antes de servir.",
    ],
  },
  {
    id: "costelinha-porco-forno",
    name: "Costelinha de porco ao forno",
    category: "prato principal",
    baseServings: 5,
    ingredients: [
      { name: "Costelinha de porco", qty: 900, unit: "g" },
      { name: "Alho", qty: 3, unit: "dente" },
      { name: "Limão", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Tempere a costelinha com sal, pimenta, alho amassado e suco de limão. Deixe marinar por pelo menos 30 minutos.",
      "Arrume numa assadeira e cubra com papel-alumínio.",
      "Asse a 190°C por 50 minutos, retire o papel e deixe dourar por mais 15-20 minutos, até a carne ficar macia e soltando do osso.",
    ],
  },

  // ---- Acompanhamentos extras (arroz, feijão, saladas, legumes, batatas) ----
  {
    id: "arroz-integral",
    name: "Arroz integral",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Arroz integral", qty: 2, unit: "xícara" },
      { name: "Óleo", qty: 1, unit: "colher de sopa" },
      { name: "Alho", qty: 1, unit: "dente" },
    ],
    instructions: [
      "Lave o arroz integral em água corrente.",
      "Aqueça o óleo numa panela e refogue o alho picado até dourar levemente.",
      "Junte o arroz e refogue por 1-2 minutos.",
      "Adicione água quente (o dobro e meio do volume de arroz) e sal a gosto.",
      "Tampe e cozinhe em fogo baixo por 35-40 minutos, até o arroz ficar macio e a água secar.",
    ],
  },
  {
    id: "arroz-a-grega",
    name: "Arroz à grega",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Arroz", qty: 2, unit: "xícara" },
      { name: "Cenoura", qty: 1, unit: "unidade" },
      { name: "Ervilha em conserva", qty: 100, unit: "g" },
      { name: "Pimentão", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Prepare um arroz branco normal (refogado no óleo/alho e cozido com água e sal).",
      "Enquanto isso, corte a cenoura e o pimentão em cubos pequenos e refogue rapidamente numa frigideira com um fio de óleo.",
      "Junte a ervilha escorrida e refogue por mais 2 minutos.",
      "Misture os legumes refogados ao arroz já pronto e sirva.",
    ],
  },
  {
    id: "feijao-preto",
    name: "Feijão preto",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Feijão preto", qty: 300, unit: "g" },
      { name: "Alho", qty: 2, unit: "dente" },
      { name: "Cebola", qty: 0.5, unit: "unidade" },
      { name: "Folha de louro", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Deixe o feijão de molho por pelo menos 4 horas (ou de um dia pro outro).",
      "Escorra e cozinhe na panela de pressão com água cobrindo por 2 dedos e a folha de louro, por cerca de 25-30 minutos após pegar pressão.",
      "Numa frigideira, refogue o alho e a cebola picados no óleo até dourar.",
      "Misture o refogado no feijão já cozido, tempere com sal e deixe ferver por mais 5-10 minutos, amassando um pouco os grãos pra engrossar o caldo.",
    ],
  },
  {
    id: "salada-tomate-cebola",
    name: "Salada de tomate e cebola",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Tomate", qty: 3, unit: "unidade" },
      { name: "Cebola", qty: 0.5, unit: "unidade" },
      { name: "Azeite", qty: 2, unit: "colher de sopa" },
    ],
    instructions: [
      "Fatie os tomates e a cebola bem fininho.",
      "Numa travessa, disponha os tomates e a cebola intercalados.",
      "Tempere com sal, azeite e, se quiser, orégano, na hora de servir.",
    ],
  },
  {
    id: "salada-repolho-cenoura",
    name: "Salada de repolho com cenoura",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Repolho", qty: 0.5, unit: "unidade" },
      { name: "Cenoura", qty: 1, unit: "unidade" },
      { name: "Limão", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Fatie o repolho bem fininho e rale a cenoura.",
      "Misture os dois numa tigela.",
      "Tempere com sal, suco de limão e um fio de azeite, e deixe descansar uns minutos antes de servir.",
    ],
  },
  {
    id: "salada-pepino-iogurte",
    name: "Salada de pepino com iogurte",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Pepino", qty: 2, unit: "unidade" },
      { name: "Iogurte natural", qty: 200, unit: "g" },
      { name: "Alho", qty: 1, unit: "dente" },
    ],
    instructions: [
      "Corte o pepino em rodelas finas (pode tirar as sementes se preferir) e tempere com uma pitada de sal, deixando descansar 10 minutos pra soltar a água.",
      "Escorra o excesso de água do pepino.",
      "Misture com o iogurte natural e o alho bem picadinho, temperando com sal e pimenta a gosto.",
    ],
  },
  {
    id: "brocolis-refogado-alho",
    name: "Brócolis refogado com alho",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Brócolis", qty: 1, unit: "unidade" },
      { name: "Alho", qty: 2, unit: "dente" },
      { name: "Azeite", qty: 1, unit: "colher de sopa" },
    ],
    instructions: [
      "Separe o brócolis em buquês e cozinhe em água fervente com sal por 3-4 minutos, até ficar macio mas ainda firme (al dente).",
      "Escorra e reserve.",
      "Numa frigideira, aqueça o azeite e doure o alho fatiado.",
      "Junte o brócolis, refogue por 2 minutos e ajuste o sal.",
    ],
  },
  {
    id: "couve-refogada",
    name: "Couve refogada",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Couve", qty: 1, unit: "maço" },
      { name: "Alho", qty: 2, unit: "dente" },
      { name: "Óleo", qty: 1, unit: "colher de sopa" },
    ],
    instructions: [
      "Lave bem as folhas de couve, retire os talos e enrole-as para cortar em tiras bem finas.",
      "Aqueça o óleo numa frigideira e doure o alho picado.",
      "Junte a couve fatiada e refogue em fogo alto por 2-3 minutos, só até murchar (sem cozinhar demais).",
      "Tempere com sal e sirva na sequência.",
    ],
  },
  {
    id: "vagem-refogada",
    name: "Vagem refogada",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Vagem", qty: 400, unit: "g" },
      { name: "Alho", qty: 1, unit: "dente" },
      { name: "Óleo", qty: 1, unit: "colher de sopa" },
    ],
    instructions: [
      "Lave as vagens e retire as pontinhas, cortando ao meio se estiverem grandes.",
      "Cozinhe em água fervente com sal por 5-6 minutos, até ficarem macias mas firmes. Escorra.",
      "Numa frigideira, aqueça o óleo e refogue o alho até dourar.",
      "Junte as vagens escorridas, refogue por 2 minutos e ajuste o sal.",
    ],
  },
  {
    id: "abobora-refogada",
    name: "Abóbora refogada",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Abóbora", qty: 500, unit: "g" },
      { name: "Cebola", qty: 0.5, unit: "unidade" },
      { name: "Óleo", qty: 1, unit: "colher de sopa" },
    ],
    instructions: [
      "Descasque a abóbora e corte em cubos médios.",
      "Aqueça o óleo numa panela e refogue a cebola picada até ficar transparente.",
      "Junte a abóbora, tempere com sal e um pouco de água.",
      "Tampe e cozinhe em fogo médio-baixo por 15-20 minutos, até ficar macia, mexendo de vez em quando.",
    ],
  },
  {
    id: "batata-assada-classica",
    name: "Batata assada ao forno (clássica)",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Batata", qty: 6, unit: "unidade" },
      { name: "Azeite", qty: 3, unit: "colher de sopa" },
      { name: "Alho", qty: 2, unit: "dente" },
    ],
    instructions: [
      "Descasque as batatas e corte em pedaços médios.",
      "Numa tigela, misture as batatas com azeite, alho picado, sal e pimenta.",
      "Espalhe numa assadeira em uma camada só, sem sobrepor.",
      "Asse a 200°C por 35-40 minutos, virando na metade do tempo, até ficarem douradas e macias por dentro.",
    ],
  },
  {
    id: "batata-rustica-ervas",
    name: "Batata rústica com ervas",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Batata", qty: 6, unit: "unidade" },
      { name: "Azeite", qty: 3, unit: "colher de sopa" },
      { name: "Alecrim", qty: 1, unit: "colher de sopa" },
    ],
    instructions: [
      "Lave bem as batatas (pode deixar a casca) e corte em gomos.",
      "Tempere com azeite, alecrim, sal e pimenta.",
      "Espalhe numa assadeira em uma camada só.",
      "Asse a 200°C por 35-40 minutos, virando na metade do tempo, até dourar.",
    ],
  },
  {
    id: "pure-batata",
    name: "Purê de batata",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Batata", qty: 6, unit: "unidade" },
      { name: "Leite", qty: 0.2, unit: "l" },
      { name: "Manteiga", qty: 30, unit: "g" },
    ],
    instructions: [
      "Descasque as batatas, corte em pedaços e cozinhe em água com sal até ficarem bem macias (cerca de 20 minutos).",
      "Escorra e amasse ainda quentes com um garfo ou espremedor.",
      "Aqueça o leite com a manteiga (sem ferver) e vá incorporando aos poucos ao purê, mexendo até ficar cremoso.",
      "Ajuste o sal e sirva quente.",
    ],
  },
  {
    id: "batata-gratinada-simples",
    name: "Batata gratinada simples",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Batata", qty: 6, unit: "unidade" },
      { name: "Creme de leite", qty: 200, unit: "g" },
      { name: "Queijo mussarela", qty: 150, unit: "g" },
    ],
    instructions: [
      "Descasque as batatas e fatie bem fininho (numa mandolina, se tiver).",
      "Numa assadeira untada, arrume as fatias em camadas, intercalando com um pouco de creme de leite e sal entre cada camada.",
      "Cubra com o queijo mussarela ralado ou fatiado.",
      "Cubra com papel-alumínio e asse a 200°C por 30 minutos; retire o papel e deixe gratinar por mais 15 minutos, até dourar e as batatas ficarem macias.",
    ],
  },
  {
    id: "farofa-simples",
    name: "Farofa simples",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Farinha de mandioca", qty: 200, unit: "g" },
      { name: "Cebola", qty: 0.5, unit: "unidade" },
      { name: "Manteiga", qty: 30, unit: "g" },
    ],
    instructions: [
      "Numa frigideira, derreta a manteiga e refogue a cebola picada até dourar.",
      "Adicione a farinha de mandioca aos poucos, mexendo sempre para não empelotar.",
      "Tempere com sal e refogue em fogo baixo por 3-5 minutos, até a farinha ficar levemente tostada.",
    ],
  },
  {
    id: "polenta-cremosa",
    name: "Polenta cremosa",
    category: "acompanhamento",
    baseServings: 4,
    ingredients: [
      { name: "Fubá", qty: 200, unit: "g" },
      { name: "Queijo parmesão", qty: 50, unit: "g" },
      { name: "Manteiga", qty: 30, unit: "g" },
    ],
    instructions: [
      "Numa panela, ferva água com sal (cerca de 4 xícaras para 200g de fubá).",
      "Adicione o fubá aos poucos, mexendo sem parar para não empelotar.",
      "Cozinhe em fogo baixo por 15-20 minutos, mexendo de vez em quando, até engrossar e soltar da panela.",
      "Desligue o fogo e misture a manteiga e o parmesão ralado até ficar cremosa.",
    ],
  },

  // ---- Sobremesas simples ----
  {
    id: "pudim-leite-condensado",
    name: "Pudim de leite condensado",
    category: "sobremesa",
    baseServings: 8,
    ingredients: [
      { name: "Leite condensado", qty: 1, unit: "lata" },
      { name: "Leite", qty: 0.4, unit: "l" },
      { name: "Ovo", qty: 3, unit: "unidade" },
      { name: "Açúcar", qty: 100, unit: "g" },
    ],
    instructions: [
      "Numa panela, derreta o açúcar em fogo baixo até virar uma calda dourada (caramelo) e forre o fundo de uma forma com furo no meio.",
      "No liquidificador, bata o leite condensado, o leite e os ovos até ficar homogêneo.",
      "Despeje a mistura na forma caramelizada.",
      "Cubra com papel-alumínio e asse em banho-maria a 180°C por 50-60 minutos, até firmar (espete um palito: deve sair limpo).",
      "Deixe esfriar completamente e leve à geladeira por pelo menos 4 horas antes de desenformar.",
    ],
  },
  {
    id: "brigadeiro-de-colher",
    name: "Brigadeiro de colher",
    category: "sobremesa",
    baseServings: 6,
    ingredients: [
      { name: "Leite condensado", qty: 1, unit: "lata" },
      { name: "Chocolate em pó", qty: 3, unit: "colher de sopa" },
      { name: "Manteiga", qty: 1, unit: "colher de sopa" },
    ],
    instructions: [
      "Numa panela, misture o leite condensado, o chocolate em pó e a manteiga.",
      "Cozinhe em fogo baixo, mexendo sempre, até engrossar levemente (uns 8-10 minutos) — não precisa desgrudar da panela como no brigadeiro de enrolar.",
      "Despeje em potinhos individuais e deixe esfriar.",
      "Leve à geladeira por pelo menos 1 hora antes de servir.",
    ],
  },
  {
    id: "arroz-doce",
    name: "Arroz doce",
    category: "sobremesa",
    baseServings: 6,
    ingredients: [
      { name: "Arroz", qty: 1, unit: "xícara" },
      { name: "Leite", qty: 1, unit: "l" },
      { name: "Açúcar", qty: 150, unit: "g" },
    ],
    instructions: [
      "Cozinhe o arroz em água até ficar macio, escorra.",
      "Numa panela, junte o arroz cozido com o leite e o açúcar.",
      "Cozinhe em fogo baixo, mexendo sempre, por cerca de 20-25 minutos, até engrossar e ficar cremoso.",
      "Sirva morno ou gelado, polvilhado com canela.",
    ],
  },
  {
    id: "banana-caramelizada",
    name: "Banana caramelizada",
    category: "sobremesa",
    baseServings: 4,
    ingredients: [
      { name: "Banana", qty: 4, unit: "unidade" },
      { name: "Açúcar", qty: 3, unit: "colher de sopa" },
      { name: "Manteiga", qty: 2, unit: "colher de sopa" },
    ],
    instructions: [
      "Corte as bananas ao meio no sentido do comprimento.",
      "Numa frigideira, derreta a manteiga com o açúcar em fogo médio até começar a caramelizar.",
      "Coloque as bananas com o corte para baixo e deixe dourar por 2-3 minutos.",
      "Vire com cuidado e doure o outro lado por mais 1-2 minutos. Sirva quente, se quiser com uma bola de sorvete.",
    ],
  },
  {
    id: "gelatina-com-frutas",
    name: "Gelatina com frutas",
    category: "sobremesa",
    baseServings: 6,
    ingredients: [
      { name: "Gelatina em pó", qty: 1, unit: "pacote" },
      { name: "Morango", qty: 200, unit: "g" },
    ],
    instructions: [
      "Prepare a gelatina conforme as instruções da embalagem, dissolvendo em água quente e depois fria.",
      "Pique os morangos em pedaços pequenos e distribua em taças ou potes individuais.",
      "Despeje a gelatina ainda líquida por cima das frutas.",
      "Leve à geladeira por pelo menos 3 horas, até firmar completamente.",
    ],
  },
  {
    id: "salada-de-frutas",
    name: "Salada de frutas",
    category: "sobremesa",
    baseServings: 4,
    ingredients: [
      { name: "Maçã", qty: 2, unit: "unidade" },
      { name: "Banana", qty: 2, unit: "unidade" },
      { name: "Mamão", qty: 0.5, unit: "unidade" },
      { name: "Laranja", qty: 2, unit: "unidade" },
    ],
    instructions: [
      "Descasque e corte todas as frutas em cubos pequenos.",
      "Esprema a laranja e reserve o suco.",
      "Misture as frutas picadas numa tigela grande.",
      "Regue com o suco de laranja (ajuda a não escurecer e dá um toque a mais) e leve à geladeira até a hora de servir.",
    ],
  },
  {
    id: "bolo-de-caneca-chocolate",
    name: "Bolo de caneca (chocolate)",
    category: "sobremesa",
    baseServings: 1,
    ingredients: [
      { name: "Farinha de trigo", qty: 4, unit: "colher de sopa" },
      { name: "Açúcar", qty: 3, unit: "colher de sopa" },
      { name: "Chocolate em pó", qty: 2, unit: "colher de sopa" },
      { name: "Leite", qty: 4, unit: "colher de sopa" },
      { name: "Óleo", qty: 2, unit: "colher de sopa" },
      { name: "Ovo", qty: 1, unit: "unidade" },
    ],
    instructions: [
      "Numa caneca grande (300ml), misture a farinha, o açúcar e o chocolate em pó.",
      "Adicione o leite, o óleo e o ovo, mexendo bem até ficar homogêneo, sem grumos.",
      "Leve ao microondas por 2 a 3 minutos (potência alta), até crescer e firmar por cima.",
      "Deixe amornar um pouco antes de comer — cuidado que a caneca fica quente.",
    ],
  },
];

// Referência de porção padrão por faixa etária/perfil, usada quando a pessoa não tem
// dieta própria cadastrada. Fator multiplica a porção-base da receita (1.0 = adulto padrão).
const PORTION_PROFILES = {
  crianca_pequena: { label: "Criança (2–6 anos)", factor: 0.45 },
  crianca: { label: "Criança (7–12 anos)", factor: 0.65 },
  adolescente: { label: "Adolescente (13–17 anos)", factor: 0.95 },
  mulher_adulta: { label: "Mulher adulta", factor: 1.0 },
  homem_adulto: { label: "Homem adulto", factor: 1.15 },
  idoso: { label: "Idoso (65+)", factor: 0.85 },
};

// Ajuste fino por nível de atividade, multiplica em cima do fator de perfil acima.
const ACTIVITY_LEVELS = {
  sedentario: { label: "Pouco ativo", factor: 0.9 },
  moderado: { label: "Ativo normal", factor: 1.0 },
  ativo: { label: "Muito ativo / treina pesado", factor: 1.15 },
};

// Converte a quantidade "de receita" (que vem em g, xícara, colher de sopa, dente, unidade...)
// em algo que dá pra efetivamente pedir/pegar no mercado brasileiro. Chave = "nome||unidade",
// igual à chave usada pra somar os ingredientes da semana.
// - mode "package": vem em embalagem fechada de tamanho fixo (perPackage = quantas unidades de
//   receita cabem numa embalagem; arredonda pra cima o nº de embalagens).
// - mode "unit": vendido solto (hortifruti), arredonda pra cima o nº de unidades.
// - mode "unit-dozen": como "unit", mas sugere dúzias quando a quantidade é grande (ovos).
// - mode "butcher": carne/peixe fresco, pesado no açougue/peixaria — arredonda pros 50g mais
//   próximos e sugere pedir por peso, não por embalagem.
const MARKET_PACKAGES = {
  "arroz||xícara": { mode: "package", perPackage: 5.5, label: "pacote de 1kg" },
  "arroz arbório||xícara": { mode: "package", perPackage: 2.5, label: "pacote de 500g" },
  "óleo||colher de sopa": { mode: "package", perPackage: 69, label: "garrafa de 900ml" },
  "azeite||colher de sopa": { mode: "package", perPackage: 38, label: "garrafa de 500ml" },
  "alho||dente": { mode: "package", perPackage: 8, label: "cabeça de alho" },
  "feijão carioca||g": { mode: "package", perPackage: 1000, label: "pacote de 1kg" },
  "feijão||g": { mode: "package", perPackage: 1000, label: "pacote de 1kg" },
  "molho de tomate||g": { mode: "package", perPackage: 340, label: "sachê de molho de tomate (340g)" },
  "queijo mussarela||g": { mode: "package", perPackage: 200, label: "pacote de queijo fatiado (200g)" },
  "farinha de rosca||g": { mode: "package", perPackage: 500, label: "pacote de farinha de rosca (500g)" },
  "creme de leite||g": { mode: "package", perPackage: 200, label: "caixinha de creme de leite (200g)" },
  "champignon||g": { mode: "package", perPackage: 200, label: "lata de champignon (200g)" },
  "macarrão||g": { mode: "package", perPackage: 500, label: "pacote de macarrão (500g)" },
  "massa de lasanha||g": { mode: "package", perPackage: 500, label: "pacote de massa de lasanha (500g)" },
  "presunto||g": { mode: "package", perPackage: 200, label: "pacote de presunto fatiado (200g)" },
  "goma de tapioca||g": { mode: "package", perPackage: 500, label: "pacote de goma de tapioca (500g)" },
  "queijo coalho||g": { mode: "package", perPackage: 250, label: "peça de queijo coalho (~250g)" },
  "queijo parmesão||g": { mode: "package", perPackage: 100, label: "pacote de queijo ralado (100g)" },
  "caldo de legumes||l": { mode: "package", perPackage: 1, label: "caixa de tabletes de caldo (rende ~1L)" },
  "farinha de trigo||g": { mode: "package", perPackage: 1000, label: "pacote de farinha de trigo (1kg)" },
  "açúcar||g": { mode: "package", perPackage: 1000, label: "pacote de açúcar (1kg)" },
  "sal||g": { mode: "package", perPackage: 1000, label: "pacote de sal (1kg)" },
  "leite||l": { mode: "package", perPackage: 1, label: "caixinha de leite (1L)" },
  "arroz integral||xícara": { mode: "package", perPackage: 5.5, label: "pacote de 1kg" },
  "feijão preto||g": { mode: "package", perPackage: 1000, label: "pacote de 1kg" },
  "farinha de mandioca||g": { mode: "package", perPackage: 500, label: "pacote de farinha de mandioca (500g)" },
  "fubá||g": { mode: "package", perPackage: 500, label: "pacote de fubá (500g)" },
  "leite condensado||lata": { mode: "unit", label: "lata de leite condensado" },
  "gelatina em pó||pacote": { mode: "unit", label: "pacote de gelatina (85g)" },
  "iogurte natural||g": { mode: "package", perPackage: 170, label: "pote de iogurte natural (170g)" },
  "ervilha em conserva||g": { mode: "package", perPackage: 170, label: "lata de ervilha (200g)" },
  "manteiga||g": { mode: "package", perPackage: 200, label: "pacote de manteiga (200g)" },

  "peito de frango||g": { mode: "butcher", label: "açougue" },
  "carne moída||g": { mode: "butcher", label: "açougue" },
  "bife (patinho ou coxão mole)||g": { mode: "butcher", label: "açougue" },
  "filé de peixe||g": { mode: "butcher", label: "peixaria" },
  "sobrecoxa de frango||g": { mode: "butcher", label: "açougue" },
  "acém||g": { mode: "butcher", label: "açougue" },
  "lombo de porco||g": { mode: "butcher", label: "açougue" },
  "bisteca de porco||g": { mode: "butcher", label: "açougue" },
  "costelinha de porco||g": { mode: "butcher", label: "açougue" },

  "cebola||unidade": { mode: "unit", label: "cebola" },
  "tomate||unidade": { mode: "unit", label: "tomate" },
  "batata||unidade": { mode: "unit", label: "batata" },
  "limão||unidade": { mode: "unit", label: "limão" },
  "pão francês||unidade": { mode: "unit", label: "pão francês" },
  "abobrinha||unidade": { mode: "unit", label: "abobrinha" },
  "cenoura||unidade": { mode: "unit", label: "cenoura" },
  "pepino||unidade": { mode: "unit", label: "pepino" },
  "alface||pé": { mode: "unit", label: "pé de alface" },
  "ovo||unidade": { mode: "unit-dozen", label: "ovo" },
  "pimentão||unidade": { mode: "unit", label: "pimentão" },
  "repolho||unidade": { mode: "unit", label: "repolho" },
  "brócolis||unidade": { mode: "unit", label: "brócolis" },
  "banana||unidade": { mode: "unit", label: "banana" },
  "maçã||unidade": { mode: "unit", label: "maçã" },
  "laranja||unidade": { mode: "unit", label: "laranja" },
  "mamão||unidade": { mode: "unit", label: "mamão" },
};
